### ISSUE TITLE
Geopandas add geometries function

### ISSUE THREAD

**Issue by PeterBetlem** [UNISvalbard/python-gis-course#1]
The below is part of a modified code to add a Svalbard_shape outline to a cartopy axis.

A minimal working example (MWE) can also be found at https://scitools.org.uk/cartopy/docs/v0.13/examples/hurricane_katrina.html

```
import geopandas as gpd
import cartopy
import matplotlib as plt


axis = plt.axes([0, 0, 1, 1],
                  projection=ccrs.LambertConformal())

Svalbard_shape=gpd.read_file('S250_Land_f.shp') # Obtained from NPI data pages

axis.add_geometries(
	Svalbard_shape['geometry'],
	crs=ccrs.epsg(25833),
	edgecolor='black',
	facecolor='gray',
	linewidth=1,
	zorder=50,
	alpha = 0.1
)
```

**Comment by PeterBetlem** [comment]
@lfrankunis let me know if this solves it; if so, feel free to close.

**Comment by lfrankunis** [comment]
Perfect, worked straight away now! Thank you!
